version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadmin

  backend:
    build: ./backend/
    container_name: backend
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      CORS_ALLOWED_ORIGINS: 'http://frontend:3000'
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: 'postgres'
      DB_SCHEMA: 'public'
      DB_USER: dbadmin
      DB_USER_PASSWORD: dbadmin
    depends_on:
      - postgres

  frontend:
    build: ./frontend/
    container_name: frontend
    ports:
      - 3000:3000
